# Generated by Django 5.1.1 on 2024-09-27 15:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('product', '0001_initial'),
        ('store', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TicketDBO',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('date_raw', models.CharField(max_length=25)),
                ('total', models.FloatField()),
                ('email', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to=settings.AUTH_USER_MODEL)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ticket_locations', to='store.storedbo')),
            ],
        ),
        migrations.CreateModel(
            name='TicketProductDBO',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.FloatField(default=0)),
                ('units', models.FloatField(default=1)),
                ('history_price', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ticket_price', to='product.productpricehistorydbo')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_tickets', to='product.productdbo')),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ticket_products', to='ticket.ticketdbo')),
            ],
        ),
        migrations.AddField(
            model_name='ticketdbo',
            name='products',
            field=models.ManyToManyField(through='ticket.TicketProductDBO', to='product.productdbo'),
        ),
    ]
