# Generated by Django 5.1.1 on 2024-09-27 19:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('product', '0001_initial'),
        ('store', '0001_initial'),
        ('ticket', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='ticketdbo',
            name='email',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='ticketdbo',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ticket_locations', to='store.storedbo'),
        ),
        migrations.AddField(
            model_name='ticketproductdbo',
            name='history_price',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ticket_price', to='product.productpricehistorydbo'),
        ),
        migrations.AddField(
            model_name='ticketproductdbo',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_tickets', to='product.productdbo'),
        ),
        migrations.AddField(
            model_name='ticketproductdbo',
            name='ticket',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ticket_products', to='ticket.ticketdbo'),
        ),
        migrations.AddField(
            model_name='ticketdbo',
            name='products',
            field=models.ManyToManyField(through='ticket.TicketProductDBO', to='product.productdbo'),
        ),
    ]
