# Generated by Django 5.1.1 on 2024-09-23 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticketdbo',
            name='total',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
