# Generated by Django 5.1.1 on 2024-09-23 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0002_ticketdbo_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticketproductdbo',
            name='units',
            field=models.FloatField(default=1),
        ),
    ]
