# Generated by Django 5.1.1 on 2024-10-24 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ticketdbo',
            options={'verbose_name': 'Ticket', 'verbose_name_plural': 'Tickets'},
        ),
        migrations.AlterModelOptions(
            name='ticketproductdbo',
            options={'verbose_name': 'Producto del ticket', 'verbose_name_plural': 'Productos de los tickets'},
        ),
        migrations.AddField(
            model_name='ticketdbo',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ticketdbo',
            name='time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
