version: '3.8'

services:
  app:
    container_name: app
    image: websource
    ports:
      - 8001:8001
    volumes:
      - mediadata:/media
      - staticdata:/static
    env_file: 'environments/staging.env'
    command: uvicorn app.wsgi:app --port=3000 --host=0.0.0.0 --reload
    restart: on-failure
    depends_on:
      - postgres
      - admin
    networks:
      - dashboard
    build:
      context: ..  # El contexto de construcción es el directorio raíz del proyecto
      dockerfile: .docker/app/Dockerfile  # Ruta al Dockerfile
  admin:
    container_name: admin
    image: websource
    ports:
      - 8000:8000
    volumes:
      - mediadata:/media
      - staticdata:/static
    env_file: 'environments/staging.env'
    depends_on:
      - postgres
    networks:
      - dashboard
    command: >
      bash -c "python3 manage.py makemigrations
      && python3 manage.py migrate
      && python3 manage.py runserver 0.0.0.0:8000"

  postgres:
    container_name: 'postgres'
    restart: always
    image: 'postgres:16.3'
    env_file: 'environments/staging.env'
    ports:
      - '5432:5432'
    volumes:
      - 'pgdata:/var/lib/postgresql/data'
    networks:
      - dashboard

  nginx:
    container_name: 'nginx'
    restart: always
    build: 'nginx/dev'  # Asegúrate de que esta ruta exista
    cap_add:
      - NET_ADMIN
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
      - URL=tickets.rudo.es
      - SUBDOMAINS=www,
      - VALIDATION=http
      - EMAIL=fdosalom@gmail.com
    volumes:
      - 'nginx:/config'
    depends_on:
      - app
    ports:
      - '443:443'
      - '80:80'  # Opcional
    networks:
      - dashboard

volumes:
  nginx:
  pgdata:
  mediadata:
  staticdata:

networks:
  dashboard:
