version: '3.8'

services:
  app:
    container_name: app
    build:
      context: ..  # El contexto de construcción es el directorio raíz del proyecto
      dockerfile: .docker/app/Dockerfile  # Ruta al Dockerfile
    ports:
      - "8000:8000"  # Puerto para Django
      - "8001:8001"  # Puerto para FastAPI
    env_file: 'environments/staging.env'  # Archivo de entorno
    image: 'websource'
    command: "supervisord -c supervisord.conf"
    volumes:
      - cachedata:/cache
      - mediadata:/media
      - staticdata:/static
    depends_on:
      - redis
      - postgres
      - cache
    networks:
      - dashboard

  celery_worker:
    container_name: 'celery_worker'
    restart: unless-stopped
    image: 'websource'
    env_file: 'environments/staging.env'
    command: 'python -m celery -A infrastructure.django worker -l debug'
    depends_on:
      - app
    networks:
      - dashboard

  celery_beat:
    container_name: 'celery_beat'
    restart: unless-stopped
    image: 'websource'
    env_file: 'environments/staging.env'
    command: 'python -m celery -A infrastructure.django beat --pidfile= -l debug'
    depends_on:
      - app
    networks:
      - dashboard

  redis:
    container_name: 'redis'
    restart: unless-stopped
    image: 'redis:3.2.0'
    command: redis-server --requirepass 12345678A
    expose:
      - '6379'
    volumes:
      - 'redisdata:/data'
    networks:
      - dashboard

  cache:
    container_name: cache
    restart: unless-stopped
    image: memcached:1.6.12-alpine
    ports:
      - '11211:11211'
    volumes:
      - 'memcached:/memcached'
    networks:
      - dashboard

  postgres:
    container_name: 'postgres'
    restart: always
    image: 'postgres:16.3'
    env_file: 'environments/staging.env'
    ports:
      - '5432:5432'
    volumes:
      - 'pgdata:/var/lib/postgresql/data'
    networks:
      - dashboard

  nginx:
    container_name: 'nginx'
    restart: always
    build: 'nginx/dev'  # Asegúrate de que esta ruta exista
    cap_add:
      - NET_ADMIN
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
      - URL=tickets.rudo.es
      - SUBDOMAINS=www,
      - VALIDATION=http
      - EMAIL=fdosalom@gmail.com
    volumes:
      - 'nginx:/config'
    depends_on:
      - app
    ports:
      - '443:443'
      - '80:80'  # Opcional
    networks:
      - dashboard

volumes:
  nginx:
  pgdata:
  redisdata:
  cachedata:
  memcached:

networks:
  dashboard:
