# Generated by Django 5.1.1 on 2024-09-23 18:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_remove_productdbo_quantity_productdbo_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productpricehistorydbo',
            name='quantity',
        ),
    ]
