# Generated by Django 5.1.1 on 2024-10-24 07:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='storedbo',
            options={'verbose_name': 'Localización', 'verbose_name_plural': 'Localizaciones'},
        ),
    ]
